modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/whizvox/CompoundOres/issues"
[[mods]]
    modId="compoundores"
    version="${file.jarVersion}"
    displayName="Compound Ores"
    #updateJSONURL="https://change.me.example.invalid/updates.json" #https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
    displayURL="https://github.com/whizvox/CompoundOres/wiki"
    logoFile="compoundores_logo.png"
    credits="Shoutouts to TheGreyGhost for his MinecraftByExample project and the guys on the MMD Discord"
    authors="whizvox"
    description='''
Spice up mining expeditions with ores containing multiple resources.
    '''
[[dependencies.compoundores]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.compoundores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
